import { Metadata } from 'next'

import { Wrapper } from '@/components/Wrapper'
import { db } from '@/lib/db'

export async function generateMetadata({
  params,
}: {
  params: {
    slug: string
  }
}): Promise<Metadata | undefined> {
  const project = await db
    .selectFrom('projects')
    .select(['latestVersion', 'name'])
    .where('slug', '=', params.slug)
    .executeTakeFirst()

  if (!project) {
    return
  }

  const version = await db
    .selectFrom('projectVersions')
    .select(['imageUrl', 'number'])
    .where('number', '=', project.latestVersion)
    .executeTakeFirst()

  if (!version) {
    return
  }

  const title = `${project.name} | codeless`
  const description = `A UI generated by AI`
  const image = version.imageUrl || ''

  return {
    title,
    description,
    openGraph: {
      title,
      description,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      creator: '@CodelessAI',
    },
  }
}

export default function CodePage({
  params,
}: {
  params: {
    slug: string
  }
}) {
  return <Wrapper slug={params.slug} />
}
